import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const permissions = [
  "dashboard.view",
  "auth.change-password",
  "auth.logout-all",
  "auth.login-history",
  "users.reset-password",
  "users.unlock",
  "users.force-change-password",
  "users.view",
  "users.create",
  "users.update",
  "users.delete",
  "roles.view",
  "roles.create",
  "roles.update",
  "roles.delete",
  "permissions.view",
  "school-profile.view",
  "school-profile.update",
  "master-data.view",
  "master-data.create",
  "master-data.update",
  "master-data.delete",
  "master-data.import",
  "master-data.export",
  "students.view",
  "students.create",
  "students.update",
  "students.delete",
  "students.import",
  "students.export",
  "students.provision-portal",
  "guardians.view",
  "guardians.create",
  "guardians.update",
  "guardians.delete",
  "guardians.import",
  "guardians.export",
  "teachers.view",
  "teachers.create",
  "teachers.update",
  "teachers.delete",
  "teachers.import",
  "teachers.export",
  "staffs.view",
  "staffs.create",
  "staffs.update",
  "staffs.delete",
  "staffs.import",
  "staffs.export",
  "teaching-assignments.view",
  "teaching-assignments.manage",
  "schedules.view",
  "schedules.manage",
  "attendance.view",
  "attendance.record",
  "attendance.update",
  "attendance.approve",
  "attendance.export",
  "attendance.print",
  "grades.view",
  "grades.input",
  "grades.update",
  "grades.approve",
  "grades.publish",
  "grades.export",
  "grades.print",
  "invoices.view",
  "invoices.create",
  "invoices.update",
  "invoices.delete",
  "invoices.issue",
  "invoices.cancel",
  "invoices.print",
  "payments.view",
  "payments.create",
  "payments.verify",
  "payments.reject",
  "payments.cancel",
  "payments.print",
  "teacher-portal.view",
  "student-portal.view",
  "guardian-portal.view",
  "expenses.view",
  "expenses.create",
  "expenses.update",
  "expenses.delete",
  "expenses.approve",
  "expenses.pay",
  "finance.view",
  "finance.export",
  "ppdb.view",
  "ppdb.create",
  "ppdb.update",
  "ppdb.delete",
  "ppdb.verify",
  "ppdb.approve",
  "ppdb.reject",
  "ppdb.convert",
  "ppdb.export",
  "ppdb.print",
  "industry-partners.view",
  "industry-partners.create",
  "industry-partners.update",
  "industry-partners.delete",
  "internships.view",
  "internships.create",
  "internships.update",
  "internships.delete",
  "internships.start",
  "internships.complete",
  "internships.cancel",
  "internships.score",
  "internship-logs.view",
  "internship-logs.create",
  "internship-logs.update",
  "internship-logs.approve",
  "internship-logs.reject",
  "alumni.view",
  "alumni.create",
  "alumni.update",
  "alumni.delete",
  "alumni.convert",
  "job-vacancies.view",
  "job-vacancies.create",
  "job-vacancies.update",
  "job-vacancies.delete",
  "job-vacancies.publish",
  "job-vacancies.close",
  "job-applications.view",
  "job-applications.update",
  "job-applications.review",
  "job-applications.accept",
  "job-applications.reject",
  "tracer-studies.view",
  "tracer-studies.create",
  "tracer-studies.update",
  "tracer-studies.delete",
  "bkk.view",
  "bkk.export",
  "announcements.view",
  "announcements.create",
  "announcements.update",
  "announcements.delete",
  "announcements.publish",
  "announcements.archive",
  "messages.view",
  "messages.send",
  "messages.read",
  "messages.delete",
  "notifications.view",
  "notifications.create",
  "notifications.read",
  "notifications.archive",
  "notification-templates.view",
  "notification-templates.create",
  "notification-templates.update",
  "notification-templates.delete",
  "reports.view",
  "reports.generate",
  "reports.download",
  "reports.export",
  "reports.cancel",
  "reports.academic",
  "reports.finance",
  "reports.ppdb",
  "reports.pkl_bkk",
  "reports.communication",
  "report-jobs.view",
  "report-jobs.create",
  "report-jobs.cancel",
  "export-history.view",
  "export-history.export",
  "counseling.view",
  "counseling.create",
  "counseling.update",
  "counseling.delete",
  "discipline.view",
  "discipline.create",
  "discipline.update",
  "discipline.delete",
  "discipline.report",
  "discipline.notify-guardian",
  "discipline.print",
  "letters.view",
  "letters.create",
  "letters.update",
  "letters.delete",
  "letters.approve",
  "letters.reject",
  "letters.issue",
  "letters.archive",
  "letters.print",
  "letters.report",
  "letters.manage-templates",
  "letters.export",
  "inventory.view",
  "inventory.create",
  "inventory.update",
  "inventory.delete",
  "inventory.borrow",
  "inventory.return",
  "inventory.maintenance",
  "inventory.export",
  "inventory.print",
  "library.view",
  "library.create",
  "library.update",
  "library.delete",
  "library.borrow",
  "library.return",
  "library.fine",
  "library.export",
  "library.print",
  "payroll.view",
  "payroll.create",
  "payroll.update",
  "payroll.approve",
  "payroll.pay",
  "payroll.print",
  "payroll.export",
  "exams.view",
  "exams.create",
  "exams.update",
  "exams.delete",
  "exams.schedule",
  "exams.participants",
  "exams.print-card",
  "exams.export",
  "learning.view",
  "learning.create",
  "learning.update",
  "learning.delete",
  "learning.assignments",
  "learning.submissions",
  "learning.grade",
  "approvals.view",
  "approvals.approve",
  "approvals.reject",
  "approvals.delegate",
  "approvals.history",
  "calendar.view",
  "calendar.create",
  "calendar.update",
  "calendar.delete",
  "calendar.publish",
];

const roles = [
  { name: "Super Admin", slug: "super-admin", description: "Full access untuk development dan operasional platform." },
  { name: "Admin Sekolah", slug: "admin-sekolah", description: "Admin operasional sekolah." },
  { name: "Kepala Sekolah", slug: "kepala-sekolah", description: "Akses monitoring manajemen sekolah." },
  { name: "Waka Kurikulum", slug: "waka-kurikulum", description: "Akses kurikulum dan master data akademik." },
  { name: "Waka Kesiswaan", slug: "waka-kesiswaan", description: "Akses kesiswaan dan data pendukung." },
  { name: "Guru", slug: "guru", description: "Akses guru." },
  { name: "Wali Kelas", slug: "wali-kelas", description: "Akses wali kelas." },
  { name: "Siswa", slug: "siswa", description: "Akses siswa." },
  { name: "Orang Tua/Wali", slug: "orang-tua-wali", description: "Akses orang tua atau wali." },
  { name: "Bendahara", slug: "bendahara", description: "Akses keuangan sekolah." },
  { name: "Staff TU", slug: "staff-tu", description: "Akses administrasi tata usaha." },
  { name: "Panitia PPDB", slug: "panitia-ppdb", description: "Akses operasional PPDB." },
  { name: "Pembimbing PKL", slug: "pembimbing-pkl", description: "Akses pembimbing PKL." },
  { name: "Admin BKK", slug: "admin-bkk", description: "Akses bursa kerja khusus." },
  { name: "Konselor BK", slug: "konselor-bk", description: "Untuk modul BK, konseling, pelanggaran, prestasi, tindak lanjut." },
  { name: "Petugas Tata Tertib", slug: "petugas-tata-tertib", description: "Untuk pelanggaran, poin, sanksi, dan disiplin." },
  { name: "Petugas Surat", slug: "petugas-surat", description: "Untuk Letter Management / surat menyurat." },
  { name: "Petugas Sarpras", slug: "petugas-sarpras", description: "Untuk Inventory / Asset Management." },
  { name: "Petugas Perpustakaan", slug: "petugas-perpustakaan", description: "Untuk Library." },
  { name: "HR Payroll", slug: "hr-payroll", description: "Untuk Payroll/slip gaji." },
  { name: "Petugas Ujian", slug: "petugas-ujian", description: "Untuk Exam Management." },
  { name: "Approver", slug: "approver", description: "Untuk Approval Center umum." },
];

const rolePermissionMap: Record<string, string[]> = {
  "super-admin": permissions,
  "admin-sekolah": permissions.filter((permission) => !permission.endsWith(".delete")),
  "kepala-sekolah": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "users.view",
    "roles.view",
    "permissions.view",
    "school-profile.view",
    "master-data.view",
    "students.view",
    "guardians.view",
    "teachers.view",
    "staffs.view",
    "teaching-assignments.view",
    "schedules.view",
    "attendance.view",
    "attendance.print",
    "grades.view",
    "grades.print",
    "finance.view",
    "invoices.view",
    "invoices.print",
    "payments.view",
    "payments.print",
    "expenses.view",
    "ppdb.view",
    "ppdb.approve",
    "ppdb.reject",
    "ppdb.print",
    "industry-partners.view",
    "internships.view",
    "internship-logs.view",
    "alumni.view",
    "job-vacancies.view",
    "job-applications.view",
    "tracer-studies.view",
    "bkk.view",
    "announcements.view",
    "messages.view",
    "notifications.view",
    "notification-templates.view",
    "reports.view",
    "report-jobs.view",
    "export-history.view",
  ],
  "waka-kurikulum": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "users.view",
    "master-data.view",
    "master-data.create",
    "master-data.update",
    "students.view",
    "teachers.view",
    "teaching-assignments.view",
    "teaching-assignments.manage",
    "schedules.view",
    "schedules.manage",
    "attendance.view",
    "attendance.record",
    "attendance.update",
    "attendance.approve",
    "attendance.print",
    "grades.view",
    "grades.input",
    "grades.update",
    "grades.approve",
    "grades.publish",
    "grades.print",
  ],
  "waka-kesiswaan": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "users.view",
    "users.reset-password",
    "users.unlock",
    "users.force-change-password",
    "master-data.view",
    "students.view",
    "students.create",
    "students.update",
    "students.provision-portal",
    "guardians.view",
    "guardians.create",
    "guardians.update",
  ],
  guru: [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "master-data.view",
    "students.view",
    "teachers.view",
    "teaching-assignments.view",
    "schedules.view",
    "attendance.view",
    "attendance.record",
    "attendance.print",
    "grades.view",
    "grades.input",
    "grades.print",
    "teacher-portal.view",
    "notifications.view",
    "notifications.read",
  ],
  "wali-kelas": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "users.view",
    "master-data.view",
    "students.view",
    "guardians.view",
    "teachers.view",
    "teaching-assignments.view",
    "schedules.view",
    "attendance.view",
    "attendance.record",
    "attendance.update",
    "attendance.approve",
    "attendance.print",
    "grades.view",
    "grades.input",
    "grades.update",
    "grades.print",
  ],
  siswa: [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "students.view",
    "student-portal.view",
    "notifications.view",
    "notifications.read",
  ],
  "orang-tua-wali": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "students.view",
    "guardians.view",
    "guardian-portal.view",
    "notifications.view",
    "notifications.read",
  ],
  bendahara: [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "master-data.view",
    "staffs.view",
    "finance.view",
    "finance.export",
    "invoices.view",
    "invoices.create",
    "invoices.update",
    "invoices.print",
    "payments.view",
    "payments.create",
    "payments.print",
    "expenses.view",
    "expenses.create",
    "expenses.approve",
    "expenses.pay",
  ],
  "staff-tu": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "users.view",
    "users.create",
    "users.update",
    "users.reset-password",
    "users.unlock",
    "users.force-change-password",
    "master-data.view",
    "master-data.create",
    "master-data.update",
    "master-data.import",
    "master-data.export",
    "students.view",
    "students.create",
    "students.update",
    "students.import",
    "students.export",
    "guardians.view",
    "guardians.create",
    "guardians.update",
    "guardians.import",
    "guardians.export",
    "teachers.view",
    "teachers.create",
    "teachers.update",
    "teachers.import",
    "teachers.export",
    "staffs.view",
    "staffs.create",
    "staffs.update",
    "staffs.import",
    "staffs.export",
    "teaching-assignments.view",
    "teaching-assignments.manage",
    "schedules.view",
    "schedules.manage",
    "attendance.view",
    "attendance.record",
    "attendance.update",
    "attendance.print",
    "grades.view",
    "grades.input",
    "grades.update",
    "grades.print",
    "invoices.view",
    "invoices.print",
    "payments.view",
    "payments.print",
    "ppdb.view",
    "ppdb.print",
    "announcements.view",
    "announcements.create",
    "announcements.update",
    "announcements.publish",
    "announcements.archive",
    "messages.view",
    "messages.send",
    "messages.read",
    "notifications.view",
    "notifications.create",
    "notifications.read",
    "notification-templates.view",
    "letters.view",
    "letters.create",
    "letters.update",
    "letters.print",
    "reports.view",
    "reports.generate",
    "report-jobs.view",
    "report-jobs.create",
    "export-history.view",
  ],
  "panitia-ppdb": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "users.view",
    "users.create",
    "users.update",
    "master-data.view",
    "students.view",
    "ppdb.view",
    "ppdb.create",
    "ppdb.update",
    "ppdb.verify",
    "ppdb.approve",
    "ppdb.reject",
    "ppdb.convert",
    "ppdb.export",
    "ppdb.print",
    "students.provision-portal",
  ],
  "pembimbing-pkl": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "users.view",
    "master-data.view",
    "students.view",
    "teachers.view",
    "industry-partners.view",
    "internships.view",
    "internships.create",
    "internships.update",
    "internships.start",
    "internships.complete",
    "internships.cancel",
    "internships.score",
    "internship-logs.view",
    "internship-logs.create",
    "internship-logs.update",
    "internship-logs.approve",
    "internship-logs.reject",
  ],
  "admin-bkk": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "users.view",
    "master-data.view",
    "students.view",
    "staffs.view",
    "industry-partners.view",
    "industry-partners.create",
    "industry-partners.update",
    "alumni.view",
    "alumni.create",
    "alumni.update",
    "alumni.convert",
    "job-vacancies.view",
    "job-vacancies.create",
    "job-vacancies.update",
    "job-vacancies.publish",
    "job-vacancies.close",
    "job-applications.view",
    "job-applications.update",
    "job-applications.review",
    "job-applications.accept",
    "job-applications.reject",
    "tracer-studies.view",
    "tracer-studies.create",
    "tracer-studies.update",
    "bkk.view",
    "bkk.export",
    "reports.view",
    "reports.generate",
    "report-jobs.view",
    "report-jobs.create",
    "export-history.view",
  ],
  "konselor-bk": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "counseling.view",
    "counseling.create",
    "counseling.update",
    "counseling.delete",
    "discipline.view",
    "discipline.create",
    "discipline.update",
    "discipline.report",
    "discipline.notify-guardian",
    "discipline.print",
  ],
  "petugas-tata-tertib": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "discipline.view",
    "discipline.create",
    "discipline.update",
    "discipline.delete",
    "discipline.report",
    "discipline.notify-guardian",
    "discipline.print",
    "students.view",
    "guardians.view",
    "notifications.view",
  ],
  "petugas-surat": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "letters.view",
    "letters.create",
    "letters.update",
    "letters.delete",
    "letters.issue",
    "letters.archive",
    "letters.print",
    "letters.report",
    "letters.manage-templates",
    "students.view",
    "teachers.view",
    "staffs.view",
    "guardians.view",
    "reports.view",
    "reports.generate",
    "report-jobs.view",
    "report-jobs.create",
    "export-history.view",
  ],
  "petugas-sarpras": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "inventory.view",
    "inventory.create",
    "inventory.update",
    "inventory.delete",
    "inventory.borrow",
    "inventory.return",
    "inventory.maintenance",
    "inventory.export",
    "inventory.print",
  ],
  "petugas-perpustakaan": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "library.view",
    "library.create",
    "library.update",
    "library.delete",
    "library.borrow",
    "library.return",
    "library.fine",
    "library.export",
    "library.print",
  ],
  "hr-payroll": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "payroll.view",
    "payroll.create",
    "payroll.update",
    "payroll.approve",
    "payroll.pay",
    "payroll.print",
    "payroll.export",
    "teachers.view",
    "staffs.view",
    "reports.view",
    "reports.generate",
    "reports.download",
    "report-jobs.view",
    "report-jobs.create",
    "export-history.view",
  ],
  "petugas-ujian": [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "exams.view",
    "exams.create",
    "exams.update",
    "exams.delete",
    "exams.schedule",
    "exams.participants",
    "exams.print-card",
    "exams.export",
    "students.view",
    "teachers.view",
    "master-data.view",
  ],
  approver: [
    "dashboard.view",
    "auth.change-password",
    "auth.logout-all",
    "auth.login-history",
    "approvals.view",
    "approvals.approve",
    "approvals.reject",
    "approvals.delegate",
    "approvals.history",
    "letters.view",
    "letters.approve",
    "letters.reject",
    "letters.print",
    "payroll.view",
    "payroll.approve",
  ],
};

function permissionGroup(key: string) {
  return key.split(".")[0] ?? "core";
}

const DEFAULT_SUPER_ADMIN_PASSWORD = "ChangeMe123!";

async function main() {
  const superAdminEmail = process.env.SEED_SUPER_ADMIN_EMAIL ?? "superadmin@nexsmsid.dev";
  const superAdminPassword = process.env.SEED_SUPER_ADMIN_PASSWORD ?? DEFAULT_SUPER_ADMIN_PASSWORD;
  const superAdminName = process.env.SEED_SUPER_ADMIN_NAME ?? "Super Admin NexSMSID";

  if (process.env.NODE_ENV === "production" && superAdminPassword === DEFAULT_SUPER_ADMIN_PASSWORD) {
    throw new Error(
      "Refusing to seed in production with the default super-admin password. " +
        "Set SEED_SUPER_ADMIN_PASSWORD (and SEED_SUPER_ADMIN_EMAIL) to non-default values before seeding.",
    );
  }

  const passwordHash = await bcrypt.hash(superAdminPassword, 12);

  const permissionRecords = new Map<string, string>();

  for (const key of permissions) {
    const permission = await prisma.permission.upsert({
      where: { key },
      update: {
        name: key,
        group: permissionGroup(key),
        description: `Permission ${key}`,
      },
      create: {
        key,
        name: key,
        group: permissionGroup(key),
        description: `Permission ${key}`,
      },
    });

    permissionRecords.set(key, permission.id);
  }

  for (const roleInput of roles) {
    const role = await prisma.role.upsert({
      where: { slug: roleInput.slug },
      update: {
        name: roleInput.name,
        description: roleInput.description,
        isActive: true,
      },
      create: {
        name: roleInput.name,
        slug: roleInput.slug,
        description: roleInput.description,
        isActive: true,
      },
    });

    await prisma.rolePermission.deleteMany({ where: { roleId: role.id } });

    for (const permissionKey of rolePermissionMap[roleInput.slug] ?? []) {
      const permissionId = permissionRecords.get(permissionKey);

      if (!permissionId) {
        continue;
      }

      await prisma.rolePermission.create({
        data: {
          roleId: role.id,
          permissionId,
        },
      });
    }
  }

  const superAdminRole = await prisma.role.findUniqueOrThrow({ where: { slug: "super-admin" } });
  // Force rotation whenever the account is (re)seeded with a known password
  const superAdmin = await prisma.user.upsert({
    where: { email: superAdminEmail },
    update: {
      name: superAdminName,
      passwordHash,
      status: "ACTIVE",
      deletedAt: null,
      forceChangePassword: true,
    },
    create: {
      email: superAdminEmail,
      name: superAdminName,
      passwordHash,
      status: "ACTIVE",
      forceChangePassword: true,
    },
  });

  await prisma.userRole.upsert({
    where: {
      userId_roleId: {
        userId: superAdmin.id,
        roleId: superAdminRole.id,
      },
    },
    update: {},
    create: {
      userId: superAdmin.id,
      roleId: superAdminRole.id,
    },
  });

  const existingSchoolProfile = await prisma.schoolProfile.findFirst();

  if (existingSchoolProfile) {
    await prisma.schoolProfile.update({
      where: { id: existingSchoolProfile.id },
      data: {
        name: existingSchoolProfile.name || "NexSMSID School",
      },
    });
  } else {
    await prisma.schoolProfile.create({
      data: {
        name: "NexSMSID School",
        description: "Profil sekolah awal untuk Phase 5.",
      },
    });
  }

  await prisma.auditLog.create({
    data: {
      actorId: superAdmin.id,
      action: "seed.people_management",
      entity: "system",
      metadata: {
        roles: roles.length,
        permissions: permissions.length,
        superAdminEmail,
      },
    },
  });

  console.log(`Seed completed. Super admin: ${superAdminEmail}`);
}


main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
