#!/usr/bin/env bash
# Generate self-signed TLS cert for local/staging HTTPS smoke (NOT for public production).
# Usage: bash scripts/setup-https-selfsigned.sh [CN]
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CN="${1:-localhost}"
SSL_DIR="$PROJECT_DIR/docker/nginx/ssl/selfsigned"
CONF_OUT="$PROJECT_DIR/docker/nginx/conf.d/https-selfsigned.conf"

mkdir -p "$SSL_DIR"

if [ ! -f "$SSL_DIR/fullchain.pem" ]; then
  echo "Generating self-signed certificate for CN=$CN ..."
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout "$SSL_DIR/privkey.pem" \
    -out "$SSL_DIR/fullchain.pem" \
    -subj "/CN=$CN/O=NexSMSID/C=ID"
fi

cat > "$CONF_OUT" <<EOF
# Auto-generated by scripts/setup-https-selfsigned.sh — do not edit manually.
server {
    listen 443 ssl;
    http2 on;
    server_name $CN;

    ssl_certificate /etc/nginx/ssl/selfsigned/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/selfsigned/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 10M;

    location /api/v1 {
        proxy_pass http://api_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        proxy_pass http://web_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

echo ""
echo "Created: $CONF_OUT"
echo "Mount docker/nginx/ssl into nginx container, then reload nginx."
echo "For Let's Encrypt on a real domain, use docker/nginx/conf.d/https.conf.example instead."
